apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    devEnvApprovers:
    - irvan-sekera
    environmentGitOwner: defindal
    gitKind: github
    gitName: github
    gitServer: https://github.com
    kanikoFlags: --skip-unused-stages --snapshotMode=redo
    provider: gke
    registry: gcr.io
  environments:
  - key: dev
    owner: prayugi
    repository: jx-gke-gsm-y
  ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: nexus
  secretStorage: gsm
  vault: {}
  webhook: lighthouse
