apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: yugi-jx-tf
    devEnvApprovers:
    - irvan-sekera
    environmentGitOwner: defindal
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "398506542991"
    kanikoFlags: --skip-unused-stages --snapshotMode=redo
    project: xl-devops
    provider: gke
    registry: gcr.io
    zone: asia-southeast1-b
  environments:
  - key: dev
    owner: prayugi
    repository: jx-gke-gsm-y
  ingress:
    domain: 35.187.231.149.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  kuberhealthy: true
  pipelineUser:
    username: dahruman
  repository: nexus
  secretStorage: gsm
  storage:
  - name: logs
    url: gs://logs-yugi-jx-tf-d8436bfd2da1
  - name: reports
    url: gs://reports-yugi-jx-tf-d8436bfd2da1
  - name: repository
    url: gs://repository-yugi-jx-tf-d8436bfd2da1
  vault: {}
  webhook: lighthouse
